package org.cas.iie.xp.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.cas.iie.xp.service.InvokingService;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-09T16:47:29.627+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "InvokingServiceImpl", 
                  wsdlLocation = "http://192.168.111.35:8080/XACML_Project_Server/webService/publish?wsdl",
                  targetNamespace = "http://impl.service.xp.iie.cas.org/") 
public class InvokingServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.xp.iie.cas.org/", "InvokingServiceImpl");
    public final static QName InvokingServiceImplPort = new QName("http://impl.service.xp.iie.cas.org/", "InvokingServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.111.35:8080/XACML_Project_Server/webService/publish?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InvokingServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.111.35:8080/XACML_Project_Server/webService/publish?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InvokingServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InvokingServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvokingServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InvokingService
     */
    @WebEndpoint(name = "InvokingServiceImplPort")
    public InvokingService getInvokingServiceImplPort() {
        return super.getPort(InvokingServiceImplPort, InvokingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvokingService
     */
    @WebEndpoint(name = "InvokingServiceImplPort")
    public InvokingService getInvokingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(InvokingServiceImplPort, InvokingService.class, features);
    }

}
