
package org.cas.iie.xp.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.cas.iie.xp.service.impl.InvokingServiceImpl;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-09T16:47:29.582+08:00
 * Generated source version: 2.7.3
 * 
 */
public final class InvokingService_InvokingServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.xp.iie.cas.org/", "InvokingServiceImpl");

    private InvokingService_InvokingServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InvokingServiceImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InvokingServiceImpl ss = new InvokingServiceImpl(wsdlURL, SERVICE_NAME);
        InvokingService port = ss.getInvokingServiceImplPort();  
        
        {
        System.out.println("Invoking getXacmlResult...");
        org.cas.iie.xp.service.UserInfo _getXacmlResult_arg0 = null;
        java.lang.String _getXacmlResult__return = port.getXacmlResult(_getXacmlResult_arg0);
        System.out.println("getXacmlResult.result=" + _getXacmlResult__return);


        }

        System.exit(0);
    }

}
