package org.cas.iie.xp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-09T16:47:29.621+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://service.xp.iie.cas.org/", name = "InvokingService")
@XmlSeeAlso({ObjectFactory.class})
public interface InvokingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getXacmlResult", targetNamespace = "http://service.xp.iie.cas.org/", className = "org.cas.iie.xp.service.GetXacmlResult")
    @WebMethod
    @ResponseWrapper(localName = "getXacmlResultResponse", targetNamespace = "http://service.xp.iie.cas.org/", className = "org.cas.iie.xp.service.GetXacmlResultResponse")
    public java.lang.String getXacmlResult(
        @WebParam(name = "arg0", targetNamespace = "")
        org.cas.iie.xp.service.UserInfo arg0
    );
}
